Repository wecode-bootcamp-korea/26-1st-Wedibooks-frontend, pull requests merged in 2021-11, with the labels that each got.

#12 [26기 옥원철] Modified: Main 페이지 관련 파일 업데이트
  package-lock.json
  package.json
  public/data/BestsellerListAll.json
  public/data/NewIssueList.json
  public/data/RecommendationList.json
  public/data/dd.md
  public/images/JYB/jyb.md
  public/images/LKB/lkb.md
  public/images/OWC/owc.md
  public/images/SHR/shr.md
  src/Routes.js
  src/components/Nav/Nav.js
  src/pages/Details/jyb.md
  src/pages/Login/lkb.md
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainSlides/BooksInSlide.js
  src/pages/Main/MainSlides/MainSlides.js
  src/pages/Main/MainSlides/MainSlides.scss
  src/pages/Main/Recommendation/Recommendation.js
  src/pages/Main/Recommendation/Recommendation.scss
  src/pages/Main/Recommendation/RecommendedBook.js
  src/pages/Main/owc.md
  src/pages/Nav/shr.md
  src/styles/common.scss
Labels: Status: 리뷰 요청

#6 [26기 설혜린] 리뷰 반영 및 Nav,Footer,Category List 구현 완료
  package-lock.json
  package.json
  public/images/SHR/lens.png
  public/index.html
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterData.js
  src/components/Nav/MenuLists.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Cartpage/CartBoxThirdLine/CartBoxThirdLine.scss
Labels: Status: 수정 요청, Status: Conflict 해결 요청

#15 [26기 옥원철 ]Modified: 추천도서 이미지 hover 시 책 정보 노출
  src/pages/Main/Recommendation/Recommendation.scss
  src/pages/Main/Recommendation/RecommendedBook.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#13 [26기 옥원철] Modified: Catetory 관련 파일 업데이트 및 충돌 해결
  public/data/CategoryList.json
  public/data/NewIssueList.json
  public/data/RecommendationList.json
  public/data/subBestseller1.json
  public/data/subBestseller2.json
  public/data/subBestseller3.json
  public/data/subBestseller4.json
  public/data/subBestseller5.json
  public/data/subBestseller6.json
  public/data/subBestseller7.json
  public/data/subBestseller8.json
  src/Routes.js
  src/pages/Categories/Categories.js
  src/pages/Categories/Categories.scss
  src/pages/Categories/SubcategoryBest/SubcategoryBest.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainSlides/BooksInSlide.js
  src/pages/Main/MainSlides/MainSlides.js
  src/pages/Main/MainSlides/MainSlides.scss
  src/pages/Main/Recommendation/Recommendation.js
  src/pages/Main/Recommendation/Recommendation.scss
  src/pages/Main/Recommendation/RecommendedBook.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#8 [26기 임기범] 마지막 리뷰주신부분 반영하고 백엔드와 통신 성공하는거 확인하고 push 합니다
  src/Routes.js
  src/components/userNav/userNav.js
  src/components/userNav/userNav.scss
  src/pages/Login/login.js
  src/pages/Login/login.scss
  src/pages/SignUp/InputData.js
  src/pages/SignUp/inputList.js
  src/pages/SignUp/signUp.js
  src/pages/SignUp/signUp.scss
Labels: Status: Accepted

#14 [26기 설혜린] cartpage 충돌 해결 후 merge 요청
  public/data/CartData.json
  src/Routes.js
  src/pages/Cartpage/BuyingButton/BuyingButton.js
  src/pages/Cartpage/BuyingButton/BuyingButton.scss
  src/pages/Cartpage/Cart.js
  src/pages/Cartpage/Cart.scss
  src/pages/Cartpage/CartBoxSecondLine/CartBoxSecondLine.js
  src/pages/Cartpage/CartBoxSecondLine/CartBoxSecondLine.scss
  src/pages/Cartpage/CartBoxThirdLine/CartBoxThirdLine.js
  src/pages/Cartpage/CartBoxThirdLine/CartBoxThirdLine.scss
  src/pages/Cartpage/DeleteButton/DeleteButton.js
  src/pages/Cartpage/DeleteButton/DeleteButton.scss
Labels: Status: 도움 요청

#19 충돌수정 완료
  src/pages/Cartpage/Cart.scss
  src/pages/Cartpage/CartBoxThirdLine/CartBoxThirdLine.scss
Labels: Status: 리뷰 요청

#20 공통.scss 수정했습니다!
  public/data/CartData.json
  public/data/NewIssueList.json
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/MenuLists.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Cartpage/Cart.scss
  src/pages/Details/BookContainer/BookContainer.js
  src/pages/Details/BookContainer/BookContainer.scss
  src/pages/Details/Details.scss
  src/pages/Details/ReviewsList/ReviewsList.scss
  src/pages/Login/login.js
  src/pages/Login/login.scss
  src/pages/SignUp/InputData.js
  src/pages/SignUp/signUp.js
  src/pages/SignUp/signUp.scss
Labels: Status: 리뷰 요청
